#!/usr/bin/env python3
"""The correctness tables of the paper, copied from the v3 result file of record, never typed.

WHY THIS EXISTS
---------------
Section "The complete pilot matrix" of paper/saltbench-v1.tex prints, beside the token, dollar and
wall tables, the same matrix read for correctness: full passes k / n per condition (P1 greenfield,
P2 brownfield, P3 specification change), the sign of the salt-diet arm's pass-rate interval against
the plain arm's (P4), its counts per model and treatment, and where each indeterminate sign comes
from. Every cell is printed by harness/systems-v3/tables_correctness_v3.py into
harness/systems-v3/RESULT-correctness-tables-v3-2026-10-01.md, as registered in
REGISTRATION-correctness-tables-v3-2026-10-01.md (declared post hoc). This script parses those
markdown tables from the result file's bytes and prints them as LaTeX rows, cell for cell, changing
only typography: "3 / 3" becomes 3/3, "(+1 censored)" and "(+1 unscorable)" become (+1c) and (+1u),
the dagger and the sign glyphs become math, and the model names are set in type. --check refuses if
the rows between any pair of markers in the tex differ from what it derives; --self-test perturbs one
pass count and one sign and requires --check to refuse.

WHAT IT DOES NOT DO
-------------------
It computes nothing. It checks the file's own arithmetic in one place: over P1-P3, conditions with a
k / n (or n = 0) + dashes + declared + unmeasured must be 200, and unmeasured must be 0.
"""
import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import descriptive_tables as dt  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RESULT = os.path.join(ROOT, "harness", "systems-v3", "RESULT-correctness-tables-v3-2026-10-01.md")
TEX = os.path.join(HERE, "saltbench-v1.tex")

SECTIONS = {
    "P1": "## P1 · greenfield",
    "P2": "## P2 · brownfield",
    "P3": "## P3 · spec-change",
    "P4": "## P4 · signs, greenfield",
    "PS": "### P4 counts, per model per treatment",
    "PQ": "### Where each `?` comes from",
}

KN = re.compile(r"^(?:(\d+) / (\d+)|n = 0)( †)?(?: \(\+(\d+) censored\))?(?: \(\+(\d+) unscorable\))?$")
SIGNS = {"+": "$+$", "−": "$-$", "=": "$=$", "?": "?", "—": "---"}


def markers(key):
    return ("%% BEGIN correctness-table-%s (generated by paper/correctness_tables.py; do not edit by hand)" % key,
            "%% END correctness-table-%s" % key)


def kn(s):
    if s in ("—", "declared", "unmeasured"):
        return dt.cell(s)
    m = KN.match(s)
    assert m, "unparsed condition cell: %r" % s
    out = "%s/%s" % (m.group(1), m.group(2)) if m.group(1) is not None else "$n=0$"
    if m.group(3):
        out += r"$^\dagger$"
    if m.group(4):
        out += " (+%sc)" % m.group(4)
    if m.group(5):
        out += " (+%su)" % m.group(5)
    return out


def rows_for(text, key):
    out = []
    prev = None
    for r in dt.md_table(text, SECTIONS[key]):
        if key == "PQ":
            out.append(" & ".join(r) + r" \\")
            continue
        model = r[0]
        label = dt.MODELS[model] if model != prev else ""
        prev = model
        if key == "PS":
            rest = r[1:]
        elif key == "P4":
            rest = [r"\texttt{%s}" % r[1]] + [SIGNS[c] for c in r[2:]]
        else:
            rest = [r"\texttt{%s}" % r[1]] + [kn(c) for c in r[2:]]
        out.append(" & ".join([label] + rest) + r" \\")
    return out


def census(text):
    n = {"kn": 0, "dash": 0, "declared": 0, "unmeasured": 0}
    for key in ("P1", "P2", "P3"):
        for r in dt.md_table(text, SECTIONS[key]):
            for c in r[2:]:
                if c == "—":
                    n["dash"] += 1
                elif c in ("declared", "unmeasured"):
                    n[c] += 1
                else:
                    assert KN.match(c), c
                    n["kn"] += 1
    return n


def extract(tex, key):
    b, e = markers(key)
    return tex[tex.index(b) + len(b):tex.index(e)].strip("\n").splitlines()


def check(text, tex):
    bad = []
    for key in SECTIONS:
        want = rows_for(text, key)
        try:
            have = extract(tex, key)
        except ValueError:
            bad.append("%s: markers absent from the tex" % key)
            continue
        if have != want:
            bad.append("%s: %d rows in the tex differ from the result file" %
                       (key, sum(1 for a, b in zip(have, want) if a != b) + abs(len(have) - len(want))))
    return bad


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()
    text = open(RESULT, encoding="utf-8").read()
    n = census(text)
    print("P1-P3 conditions: k/n %d · dash %d · declared %d · unmeasured %d = %d" %
          (n["kn"], n["dash"], n["declared"], n["unmeasured"], sum(n.values())), file=sys.stderr)
    if sum(n.values()) != 200 or n["unmeasured"]:
        print("REFUSED: P1-P3 do not sum to 200 conditions, or a condition is unmeasured", file=sys.stderr)
        return 1
    if a.self_test:
        tex = open(TEX, encoding="utf-8").read()
        base = check(text, tex)
        if base:
            print("SELF-TEST VOID: the unperturbed check is not green (%s)" % base[0], file=sys.stderr)
            return 1
        for old, new, want in (("| claude-opus-5 | FreeList | 3 / 3 | 2 / 3 |", "| claude-opus-5 | FreeList | 3 / 3 | 1 / 3 |", "P1"),
                               ("| claude-opus-5 | FreeList | − | = | − |", "| claude-opus-5 | FreeList | ? | = | − |", "P4")):
            mutant = text.replace(old, new, 1)
            assert mutant != text, old
            bad = check(mutant, tex)
            if bad != ["%s: 1 rows in the tex differ from the result file" % want]:
                print("SELF-TEST FAILED: a perturbed %s cell was not refused (%s)" % (want, bad), file=sys.stderr)
                return 1
            print("SELF-TEST OK: perturbed %s cell refused" % want, file=sys.stderr)
        return 0
    if a.check:
        bad = check(text, open(TEX, encoding="utf-8").read())
        for b in bad:
            print("REFUSED: " + b, file=sys.stderr)
        if bad:
            return 1
        print("OK: all %d blocks in the tex equal the result file" % len(SECTIONS), file=sys.stderr)
        return 0
    for key in SECTIONS:
        b, e = markers(key)
        print(b)
        print("\n".join(rows_for(text, key)))
        print(e)
    return 0


if __name__ == "__main__":
    sys.exit(main())
