#!/usr/bin/env python3
"""The dollar and wall tables of the paper, copied from the v3 result file of record, never typed.

WHY THIS EXISTS
---------------
Section "The complete pilot matrix" of paper/saltbench-v1.tex prints, beside the token tables that
paper/descriptive_tables.py copies, the same matrix in modelled list-price dollars ($1-$4) and in
wall seconds (W1-W4), with each ratio table's sign counts, and the Opus head-versus-subagent split
(S1). Every cell is printed by harness/systems-v3/tables_v3.py into
harness/systems-v3/RESULT-cost-tables-v3-2026-09-29.md, as registered in
REGISTRATION-cost-tables-v3-2026-09-29.md. This script parses those markdown tables from the result
file's bytes and prints them as LaTeX rows, cell for cell, changing only typography (the dollar sign,
the thousands comma, the unit suffix, the bound marks, the model names). --check refuses if the rows
between any pair of markers in the tex differ from what it derives; --self-test perturbs one digit of
each currency and requires --check to refuse.

WHAT IT DOES NOT DO
-------------------
It computes nothing. It checks the file's own arithmetic in one place: in $1-$3 and in W1-W3,
numbers + dashes + declared + unmeasured must be 200 per currency.
"""
import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import descriptive_tables as dt  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RESULT = os.path.join(ROOT, "harness", "systems-v3", "RESULT-cost-tables-v3-2026-09-29.md")
TEX = os.path.join(HERE, "saltbench-v1.tex")

SECTIONS = {
    "D1": "## $1 · greenfield",
    "D2": "## $2 · brownfield",
    "D3": "## $3 · spec-change",
    "D4": "## $4 · salt-diet ÷ plain, greenfield",
    "DS": "### $4 sign counts",
    "W1": "## W1 · greenfield",
    "W2": "## W2 · brownfield",
    "W3": "## W3 · spec-change",
    "W4": "## W4 · salt-diet ÷ plain, greenfield",
    "WS": "### W4 sign counts",
    "S1": "## S1 · Opus: the share",
}


def markers(key):
    return ("%% BEGIN cost-table-%s (generated by paper/cost_tables.py; do not edit by hand)" % key,
            "%% END cost-table-%s" % key)


def cell(s):
    s = re.sub(r" s$", "", s)
    s = s.replace("$", r"\$")
    s = s.replace("%", r"\%")
    return dt.cell(s)


def rows_for(text, key):
    out = []
    prev = None
    rows = dt.md_table(text, SECTIONS[key])
    for r in rows:
        if key == "S1":
            # problem | field | arm | extras | n | share T | share $
            label = r"\texttt{%s}" % r[0] if r[0] != prev else ""
            prev = r[0]
            out.append(" & ".join([label, r[1], r"\arm{%s}" % r[2], r[3], r[4], cell(r[5]), cell(r[6])]) + r" \\")
            continue
        model = r[0]
        label = dt.MODELS[model] if model != prev else ""
        prev = model
        rest = r[1:]
        if key in ("DS", "WS"):
            rest = [rest[0], rest[1], rest[2], cell(rest[3]), rest[4]]
        else:
            rest = [r"\texttt{%s}" % rest[0]] + [cell(c) for c in rest[1:]]
        out.append(" & ".join([label] + rest) + r" \\")
    return out


def census(text, keys, pat):
    n = {"number": 0, "dash": 0, "declared": 0, "unmeasured": 0}
    for key in keys:
        for r in dt.md_table(text, SECTIONS[key]):
            for c in r[2:]:
                if c == "—":
                    n["dash"] += 1
                elif c in ("declared", "unmeasured"):
                    n[c] += 1
                else:
                    assert re.match(pat, c), c
                    n["number"] += 1
    return n


def extract(tex, key):
    b, e = markers(key)
    return tex[tex.index(b) + len(b):tex.index(e)].strip("\n").splitlines()


def check(text, tex):
    bad = []
    for key in SECTIONS:
        want = rows_for(text, key)
        try:
            have = extract(tex, key)
        except ValueError:
            bad.append("%s: markers absent from the tex" % key)
            continue
        if have != want:
            bad.append("%s: %d rows in the tex differ from the result file" %
                       (key, sum(1 for a, b in zip(have, want) if a != b) + abs(len(have) - len(want))))
    return bad


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()
    text = open(RESULT, encoding="utf-8").read()
    for name, keys, pat in (("$1-$3", ("D1", "D2", "D3"), r"^(≥ )?\$[\d,]+\.\d\d$"),
                            ("W1-W3", ("W1", "W2", "W3"), r"^(≥ )?[\d,]+ s$")):
        n = census(text, keys, pat)
        print("%s cells: numbers %d · dash %d · declared %d · unmeasured %d = %d" %
              (name, n["number"], n["dash"], n["declared"], n["unmeasured"], sum(n.values())), file=sys.stderr)
        if sum(n.values()) != 200:
            print("REFUSED: %s do not sum to 200 conditions" % name, file=sys.stderr)
            return 1
    if a.self_test:
        tex = open(TEX, encoding="utf-8").read()
        base = check(text, tex)
        if base:
            print("SELF-TEST VOID: the unperturbed check is not green (%s)" % base[0], file=sys.stderr)
            return 1
        for old, new, want in (("≥ $6.21", "≥ $6.22", "D1"), ("≥ 864 s", "≥ 865 s", "W1"),
                               ("| 20.3 % |", "| 20.4 % |", "S1")):
            mutant = text.replace(old, new, 1)
            assert mutant != text, old
            bad = check(mutant, tex)
            if bad != ["%s: 1 rows in the tex differ from the result file" % want]:
                print("SELF-TEST FAILED: a perturbed %s digit was not refused (%s)" % (want, bad), file=sys.stderr)
                return 1
            print("SELF-TEST OK: perturbed %s digit refused" % want, file=sys.stderr)
        return 0
    if a.check:
        bad = check(text, open(TEX, encoding="utf-8").read())
        for b in bad:
            print("REFUSED: " + b, file=sys.stderr)
        if bad:
            return 1
        print("OK: all %d blocks in the tex equal the result file" % len(SECTIONS), file=sys.stderr)
        return 0
    for key in SECTIONS:
        b, e = markers(key)
        print(b)
        print("\n".join(rows_for(text, key)))
        print(e)
    return 0


if __name__ == "__main__":
    sys.exit(main())
