#!/usr/bin/env python3
"""The four descriptive tables of the paper, copied from the result file of record, never typed.

WHY THIS EXISTS
---------------
Section "The complete pilot matrix" of paper/saltbench-v1.tex prints four tables of median total
tokens (T1 greenfield, T2 brownfield, T3 specification change, T4 salt-diet / plain ratios with the
per-model sign counts). Every cell is printed by harness/systems-v3/tables_v2.py into
harness/systems-v3/RESULT-descriptive-tables-v2-2026-09-27.md, as registered in
REGISTRATION-descriptive-tables-v2-2026-09-27.md. This script parses those markdown tables from the
result file's bytes and prints them as LaTeX rows, cell for cell, changing only typography (the
thousands comma, the bound marks, the model names). With --check it extracts the rows between each
pair of markers in the tex and refuses if they differ from what it derives, so the tex cannot drift
from the result file without a red. --self-test perturbs one digit of the parsed file and requires
--check's comparison to refuse.

WHAT IT DOES NOT DO
-------------------
It computes nothing. No median, ratio or sign count is derived here; each is the result file's own.
It checks the file's own arithmetic in one place only: numbers + dashes + declared + unmeasured over
T1-T3 must be 200, and the counts are printed.
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RESULT = os.path.join(ROOT, "harness", "systems-v3", "RESULT-descriptive-tables-v2-2026-09-27.md")
TEX = os.path.join(HERE, "saltbench-v1.tex")

SECTIONS = {
    "T1": "## T1 · greenfield",
    "T2": "## T2 · brownfield",
    "T3": "## T3 · spec-change",
    "T4": "## T4 · salt-diet ÷ plain, greenfield",
    "S": "### T4 sign counts",
}
MODELS = {
    "claude-opus-5": r"\texttt{claude-opus-5}",
    "claude-sonnet-5": r"\texttt{claude-sonnet-5}",
    "gemini-3.1-pro-high": r"\texttt{gemini-3.1-pro-high}",
    "gemini-3.8-flash-high": r"\texttt{gemini-3.8-flash-high}",
}


def markers(key):
    return ("%% BEGIN descriptive-table-%s (generated by paper/descriptive_tables.py; do not edit by hand)" % key,
            "%% END descriptive-table-%s" % key)


def md_table(text, heading):
    i = text.index(heading)
    rows = []
    started = False
    for line in text[i:].splitlines()[1:]:
        if line.startswith("|"):
            started = True
            rows.append([c.strip() for c in line.strip().strip("|").split("|")])
        elif started:
            break
    return rows[2:]  # drop the header and the |---| rule


def cell(s):
    s = s.replace("≥ ", r"$\geq$\,").replace("≤ ", r"$\leq$\,")
    s = re.sub(r"(\d),(\d)", r"\1{,}\2", s)
    s = re.sub(r"(\d),(\d)", r"\1{,}\2", s)
    if s == "—":
        return "---"
    if s in ("declared", "unmeasured"):
        return r"\emph{%s}" % s
    m = re.match(r"bounds only \((.*)\)$", s)
    if m:
        return r"(%s)" % m.group(1)
    return s


def rows_for(text, key):
    out = []
    prev = None
    for r in md_table(text, SECTIONS[key]):
        model = r[0]
        label = MODELS[model] if model != prev else ""
        prev = model
        rest = r[1:]
        if key == "S":
            # model | treatment | k of m | indeterminate | median | bounded
            rest = [rest[0], rest[1], rest[2], cell(rest[3]), rest[4]]
        else:
            rest = [rest[0]] + [cell(c) for c in rest[1:]]
            rest[0] = r"\texttt{%s}" % rest[0]
        out.append(" & ".join([label] + rest) + r" \\")
    return out


def census(text):
    n = {"number": 0, "dash": 0, "declared": 0, "unmeasured": 0}
    for key in ("T1", "T2", "T3"):
        for r in md_table(text, SECTIONS[key]):
            for c in r[2:]:
                if c == "—":
                    n["dash"] += 1
                elif c in ("declared", "unmeasured"):
                    n[c] += 1
                else:
                    assert re.match(r"^(≥ )?[\d,]+$", c), c
                    n["number"] += 1
    return n


def extract(tex, key):
    b, e = markers(key)
    return tex[tex.index(b) + len(b):tex.index(e)].strip("\n").splitlines()


def check(text, tex):
    bad = []
    for key in SECTIONS:
        want = rows_for(text, key)
        try:
            have = extract(tex, key)
        except ValueError:
            bad.append("%s: markers absent from the tex" % key)
            continue
        if have != want:
            bad.append("%s: %d rows in the tex differ from the result file" %
                       (key, sum(1 for a, b in zip(have, want) if a != b) + abs(len(have) - len(want))))
    return bad


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()
    text = open(RESULT, encoding="utf-8").read()
    n = census(text)
    print("T1-T3 cells: numbers %(number)d · dash %(dash)d · declared %(declared)d · unmeasured %(unmeasured)d" % n,
          "= %d" % sum(n.values()), file=sys.stderr)
    if sum(n.values()) != 200:
        print("REFUSED: T1-T3 do not sum to 200 conditions", file=sys.stderr)
        return 1
    if a.self_test:
        tex = open(TEX, encoding="utf-8").read()
        base = check(text, tex)
        if base:
            print("SELF-TEST VOID: the unperturbed check is not green (%s)" % base[0], file=sys.stderr)
            return 1
        mutant = text.replace("6,113,449", "6,113,448", 1)
        assert mutant != text
        bad = check(mutant, tex)
        if bad != ["T1: 1 rows in the tex differ from the result file"]:
            print("SELF-TEST FAILED: a perturbed digit was not refused", file=sys.stderr)
            return 1
        print("SELF-TEST OK: perturbed digit refused (%s)" % bad[0], file=sys.stderr)
        return 0
    if a.check:
        bad = check(text, open(TEX, encoding="utf-8").read())
        for b in bad:
            print("REFUSED: " + b, file=sys.stderr)
        if bad:
            return 1
        print("OK: all five blocks in the tex equal the result file", file=sys.stderr)
        return 0
    for key in SECTIONS:
        b, e = markers(key)
        print(b)
        print("\n".join(rows_for(text, key)))
        print(e)
    return 0


if __name__ == "__main__":
    sys.exit(main())
