#!/usr/bin/env python3
"""The complete-pilot-matrix table of the paper, derived and checked rather than typed.

WHY THIS EXISTS
---------------
Section "The complete pilot matrix" of paper/saltbench-v1.tex prints twenty rows, one per
(model, task form, treatment), each carrying its DONE / INEXPRESSIBLE / DECLARED counts and the
result of record those counts rest on. Every row is a reading of the matrix census
(harness/systems-v3/CENSUS-full-matrix-2026-09-14.md) and its dated addenda, and a table typed
by hand from a 1,300-line census is a table nobody can audit.

This script holds the twenty rows with the census section each was read from, checks that
their sums equal the census's own LIVE row (parsed from the census file's bytes, never typed
here), checks the per-row arithmetic (every row is ten conditions; a statement row carries
Paxos's two inexpressible conditions), and prints the LaTeX rows. With --check it extracts
the rows between the markers in the tex and refuses if they differ from what it derives, so
the tex cannot drift from the census without a red. --self-test plants a wrong count and
requires the refusal to fire.

WHAT IT DOES NOT DO
-------------------
It does not read the result files. Which conditions each result of record covers is the
census's claim (its section C6 item 1 says the census is built from each result's own
population statement), and this script inherits that claim with its citation.
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CENSUS = os.path.join(ROOT, "harness", "systems-v3", "CENSUS-full-matrix-2026-09-14.md")
TEX = os.path.join(HERE, "saltbench-v1.tex")
BEGIN = "% BEGIN matrix-census-table (generated by paper/matrix_census_table.py; do not edit by hand)"
END = "% END matrix-census-table"

# (model, form, treatment, done, inexpressible, declared, result-of-record files, census sections)
# Files are under harness/systems-v3/ with the RESULT- prefix and the .md suffix elided.
ROWS = [
    ("claude-opus-5", "greenfield", "none", 10, 0, 0,
     ["matrix-opus-1-2026-09-08"], "C4"),
    ("claude-opus-5", "greenfield", "statement", 8, 2, 0,
     ["statement-arm-2026-09-09"], "C4"),
    ("claude-opus-5", "greenfield", "spec-change", 10, 0, 0,
     ["p1-specchange-2026-09-10"], "C4"),
    ("claude-opus-5", "brownfield", "none", 10, 0, 0,
     ["claude-blockO-2026-09-21"], "addendum 13"),
    ("claude-opus-5", "brownfield", "statement", 8, 2, 0,
     ["claude-blockOS-2026-09-21"], "addenda 17 and 18"),
    ("claude-sonnet-5", "greenfield", "none", 10, 0, 0,
     ["claude-blockSG-2026-09-21"], "addendum 14"),
    ("claude-sonnet-5", "greenfield", "statement", 8, 2, 0,
     ["claude-blockSS-2026-09-21"], "addendum 15"),
    ("claude-sonnet-5", "greenfield", "spec-change", 7, 0, 3,
     ["claude-blockSC-2026-09-21"], "addenda 18 and 19"),
    ("claude-sonnet-5", "brownfield", "none", 10, 0, 0,
     ["claude-blockSB-2026-09-19"], "addenda 11 and 12"),
    ("claude-sonnet-5", "brownfield", "statement", 8, 2, 0,
     ["claude-blockSBS-2026-09-21"], "addendum 16"),
    ("gemini-3.1-pro-high", "greenfield", "none", 10, 0, 0,
     ["p1-greenfield-2026-09-13", "gemini-level6-2026-09-17"], "C4 and addendum 9"),
    ("gemini-3.1-pro-high", "greenfield", "statement", 8, 2, 0,
     ["p1-greenfield-2026-09-13", "gemini-level6-2026-09-17"], "C4 and addendum 9"),
    ("gemini-3.1-pro-high", "greenfield", "spec-change", 10, 0, 0,
     ["gemini-level8-chainD-2026-09-24", "gemini-level8-chainF-2026-09-24"], "addenda 20, 22 and 23"),
    ("gemini-3.1-pro-high", "brownfield", "none", 10, 0, 0,
     ["gemini-brownfield-level4-2026-09-14", "gemini-level7-2026-09-19"], "addenda 6 and 10"),
    ("gemini-3.1-pro-high", "brownfield", "statement", 8, 2, 0,
     ["gemini-level7-2026-09-19"], "addendum 10"),
    ("gemini-3.8-flash-high", "greenfield", "none", 10, 0, 0,
     ["gemini-flash-level5-2026-09-15", "gemini-level6-2026-09-17"], "addenda 5, 7 and 9"),
    ("gemini-3.8-flash-high", "greenfield", "statement", 8, 2, 0,
     ["gemini-flash-level5-2026-09-15", "gemini-level6-2026-09-17"], "addenda 7 and 9"),
    ("gemini-3.8-flash-high", "greenfield", "spec-change", 10, 0, 0,
     ["gemini-level8-chainD-2026-09-24", "gemini-level8-chainF-2026-09-24"], "addenda 20, 21 and 23"),
    ("gemini-3.8-flash-high", "brownfield", "none", 10, 0, 0,
     ["gemini-level6-2026-09-17", "gemini-level7-2026-09-19"], "addenda 9 and 10"),
    ("gemini-3.8-flash-high", "brownfield", "statement", 8, 2, 0,
     ["gemini-level7-2026-09-19"], "addenda 10 and 24"),
]

LIVE_RE = re.compile(
    r"LIVE \(ADDENDUM (\d+)\)\s+DONE (\d+) · OWED\s+(\d+) · BLOCKED\s+(\d+) · INEXPR (\d+) · DECLARED (\d+)"
)


def census_live(path):
    """The census's own LIVE row, from its bytes. Refuses if there is not exactly one."""
    with open(path, "rb") as fh:
        text = fh.read().decode("utf-8")
    hits = LIVE_RE.findall(text)
    if len(hits) != 1:
        raise SystemExit("REFUSE: expected exactly one LIVE row in the census, found %d" % len(hits))
    add, done, owed, blocked, inexpr, declared = (int(x) for x in hits[0])
    return {"addendum": add, "done": done, "owed": owed, "blocked": blocked,
            "inexpr": inexpr, "declared": declared}


def check_rows(rows, live):
    problems = []
    if len(rows) != 20:
        problems.append("row count %d, expected 20 (4 models x 5 form-treatment pairs)" % len(rows))
    for m, f, t, d, i, x, files, sec in rows:
        if d + i + x != 10:
            problems.append("row %s/%s/%s sums to %d, not 10" % (m, f, t, d + i + x))
        if (t == "statement") != (i == 2):
            problems.append("row %s/%s/%s: only a statement row carries Paxos's 2 inexpressible" % (m, f, t))
        for name in files:
            p = os.path.join(ROOT, "harness", "systems-v3", "RESULT-%s.md" % name)
            if not os.path.isfile(p):
                problems.append("row %s/%s/%s cites a file that does not exist: %s" % (m, f, t, p))
    done = sum(r[3] for r in rows)
    inexpr = sum(r[4] for r in rows)
    declared = sum(r[5] for r in rows)
    for key, mine in (("done", done), ("inexpr", inexpr), ("declared", declared)):
        if mine != live[key]:
            problems.append("table %s = %d, census LIVE row %s = %d" % (key, mine, key, live[key]))
    if live["owed"] != 0 or live["blocked"] != 0:
        problems.append("census LIVE row still carries OWED %d / BLOCKED %d; the table has no column for them"
                        % (live["owed"], live["blocked"]))
    if done + inexpr + declared + live["owed"] + live["blocked"] != 200:
        problems.append("states do not sum to 200")
    return problems


def latex_rows(rows):
    out = []
    last_model = None
    for m, f, t, d, i, x, files, sec in rows:
        model = r"\texttt{%s}" % m if m != last_model else ""
        last_model = m
        cite = r"\newline ".join(r"\texttt{%s}" % name for name in files)
        out.append("%s & %s & %s & %d & %d & %d & %s \\\\" % (model, f, t, d, i, x, cite))
    done = sum(r[3] for r in rows)
    inexpr = sum(r[4] for r in rows)
    declared = sum(r[5] for r in rows)
    out.append(r"\midrule")
    out.append(r"all four models & & & %d & %d & %d & 200 conditions \\" % (done, inexpr, declared))
    return "\n".join(out)


def tex_block(path):
    with open(path, "rb") as fh:
        text = fh.read().decode("ascii")
    a = text.count(BEGIN)
    b = text.count(END)
    if a != 1 or b != 1:
        raise SystemExit("REFUSE: expected one BEGIN and one END marker in the tex, found %d and %d" % (a, b))
    start = text.index(BEGIN) + len(BEGIN)
    end = text.index(END)
    return text[start:end].strip()


def norm(s):
    return re.sub(r"\s+", " ", s.strip())


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("--census", default=CENSUS)
    ap.add_argument("--check", metavar="TEX", nargs="?", const=TEX,
                    help="compare the rows in the tex against the derived rows; red on any difference")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args(argv)

    live = census_live(args.census)
    if args.self_test:
        bad = [list(r) for r in ROWS]
        bad[0][3] = 9
        bad = [tuple(r) for r in bad]
        p = check_rows(bad, live)
        if not any("table done" in x for x in p) or not any("sums to 9" in x for x in p):
            raise SystemExit("SELF-TEST FAIL: a planted wrong count was not refused: %r" % p)
        if check_rows(ROWS, live):
            raise SystemExit("SELF-TEST FAIL: the real rows do not pass: %r" % check_rows(ROWS, live))
        print("self-test OK: a planted wrong count is refused, the real rows pass, LIVE = ADDENDUM %d"
              % live["addendum"])
        return 0

    problems = check_rows(ROWS, live)
    if problems:
        for p in problems:
            print("REFUSE:", p)
        return 1
    generated = latex_rows(ROWS)
    if args.check:
        block = tex_block(args.check)
        if norm(block) != norm(generated):
            print("REFUSE: the table in %s differs from the derived rows" % args.check)
            print("--- derived\n%s\n--- in the tex\n%s" % (generated, block))
            return 1
        print("OK: the tex table equals the derived rows; totals DONE %d INEXPR %d DECLARED %d = census LIVE (ADDENDUM %d)"
              % (live["done"], live["inexpr"], live["declared"], live["addendum"]))
        return 0
    print(generated)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
